# Copyright (c) 2020-2026 CRS4
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
rule_files:
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: lifemonitor_backend
  static_configs:
  - targets:
    - lm:9090
- job_name: lifemonitor_worker
  static_configs:
  - targets:
    - worker:9191
- job_name: lifemonitor_websocket
  static_configs:
  - targets:
    - websocket:8000
  scheme: https
  tls_config:
    insecure_skip_verify: true

# alerting:
#   alertmanagers:
#   - kubernetes_sd_configs:
#       - role: pod
#     tls_config:
#       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_namespace]
#       regex: monitoring
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_app]
#       regex: prometheus
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_label_component]
#       regex: alertmanager
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
#       regex: .*
#       action: keep
#     - source_labels: [__meta_kubernetes_pod_container_port_number]
#       regex:
#       action: drop
