# set upstream server
upstream lm_app {
  # fail_timeout=0 means we always retry an upstream even if it failed
  # to return a good HTTP response
  server lm:8000 fail_timeout=0;
}

server {
  listen 8443 ssl default_server;
  client_max_body_size 4G;
  # set the correct host(s) for your site
  #server_name localhost;
  etag on;

  client_body_timeout 120s;
  client_header_timeout 120s;
  send_timeout 120s;
  keepalive_timeout 65s;

  ssl_certificate /nginx/certs/lm.crt;
  ssl_certificate_key /nginx/certs/lm.key;

  # force HTTP traffic to HTTPS
  error_page 497 https://$host:$server_port$request_uri;

  # set static files location
  location /static/ {
    root /app/lifemonitor;
  }

    # wrap api
  location /api/ {
    # rewrite request
    rewrite ^/api/(.*)$ /$1 break;

    # disable redirects
    proxy_redirect          off;

    # rewrite headers
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Host $host:$server_port;

    # various proxy settings
    proxy_connect_timeout   600;
    proxy_read_timeout      600;
    proxy_send_timeout      600;
    #proxy_intercept_errors  on;

    # set the upstream server
    proxy_pass https://lm_app;
  }

  # if the path matches to root, redirect to the account page
  location = / {
    return 301 https://$host:$server_port/account/;
  }

  # set proxy location
  location / {

    # various proxy settings
    proxy_connect_timeout   600;
    proxy_read_timeout      600;
    proxy_send_timeout      600;
    #proxy_intercept_errors  on;

    access_log true;
    # resolver 127.0.0.11 ipv6=off valid=30s;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host:$server_port;
    # we don't want nginx trying to do something clever with
    # redirects, we set the Host: header above already.
    proxy_redirect off;
    proxy_pass https://lm_app;
  }
}
